= Driving Tracker - Fahrtenverwaltung
:author: Jan Brunner
:revnumber: 1.0
:revdate: {docdate}
:revremark: JavaFX Anwendung zur Fahrtenverwaltung für Fahrschüler
:encoding: utf-8
:lang: de
:doctype: article
:revealjs_width: 1408
:revealjs_height: 792
:source-highlighter: highlightjs
:iconfont-remote!:
:iconfont-name: fonts/fontawesome/css/all
ifdef::env-ide[]
:imagesdir: ../images
endif::[]
ifndef::env-ide[]
:imagesdir: images
endif::[]
:title-slide-transition: fade
:title-slide-transition-speed: slow
:transition: fade
:transition-speed: slow

== Driving Tracker

[.text-center]
Digitale Fahrtenverwaltung für Fahrschüler

_Vereinfachte Verwaltung gefahrener Kilometer und Fahrtbedingungen_

[transition]

== Ausgangssituation

Fahrschüler dokumentieren Fahrten für Führerschein:

* Erforderlich für L17 & Normalführerschein
* 2-3 Fahrten pro Woche durchschnittlich
* Circa 120 Einträge pro Jahr

[transition]

== Das Problem

Analoge Verwaltung heute:

* Manuelle Notizen auf Zetteln
* Unorganisierte Excel-Dateien
* Überblick geht schnell verloren
* Zeitaufwändig und fehleranfällig

[transition]

== Anforderungen an die Lösung

Funktional:

* Neue Fahrten erfassen und speichern
* Fahrten bearbeiten oder löschen
* Gesamtkilometer und Durchschnittswerte anzeigen
* Daten persistent speichern

[transition]

== Anforderungen (Fortsetzung)

Nicht-funktional:

* Sichere Datenspeicherung
* Zwei-Tab Interface: Erfassung & Statistik
* Intuitive und einfache Bedienung

[transition]

== Lösungsansatz

JavaFX-Anwendung für Fahrtenverwaltung

* Zentrale Datenbank statt Zettel
* Strukturierte Erfassung aller Fahrtdaten
* Automatische Statistikberechnung
* Sichere Datenpersistenz

[transition]

== Use-Cases im Überblick

[plantuml, usecase, svg]
----
@startuml DrivingTracker_UseCase
left to right direction

actor Driver

package "Driving Tracker" {
    usecase UC1 as "Fahrt erfassen"
    usecase UC2 as "Fahrt bearbeiten"
    usecase UC3 as "Fahrt löschen"
    usecase UC4 as "Fahrten anzeigen"
    usecase UC5 as "Filtern"
    usecase UC6 as "Sortieren"
    usecase UC7 as "Statistiken"
    usecase UC8 as "Importieren"
    usecase UC9 as "Exportieren"
}

Driver --> UC1
Driver --> UC2
Driver --> UC3
Driver --> UC4
Driver --> UC5
Driver --> UC6
Driver --> UC7
Driver --> UC8
Driver --> UC9

UC1 .> UC4 : <<include>>
UC2 .> UC4 : <<include>>
UC3 .> UC4 : <<include>>
@enduml
----

[transition]

== Systemarchitektur

[plantuml, classdia, svg]
----
@startuml
left to right direction

class Trip {
    -int id
    -LocalDate date
    -double startKm / endKm
    -String startCity / endCity
    -HashSet<Condition> conditions
    
    +getKilometers()
}

class TripManager {
    -ObservableList<Trip> trips
    -DatabaseConnection connection
    
    +addTrip() +deleteTrip()
    +getSumKilometers()
}

class DatabaseConnection {
    +insertIntoDB()
    +getAllTrips()
}

enum Condition {
    Day / Night
    Rain / Dry / Wet
    Fog / Snow / Ice
}

Trip "1" --- "*" Condition
TripManager "1" --- "*" Trip
TripManager "1" --- "1" DatabaseConnection

@enduml
----

[transition]

== Datenbankmodell

[plantuml, erd, svg]
----
@startuml DrivingTracker_ERD

entity TRIP {
    * ID : INT <<PK>>
    ---
    DATE, START_KM, END_KM
    START_CITY, END_CITY
}

entity TRIP_CONDITION {
    * TRIP_ID : INT <<FK>>
    * CONDITION : VARCHAR(50)
}

TRIP ||--o{ TRIP_CONDITION

@enduml
----

Relationale Struktur für sichere Datenpersistenz

[transition]

== Technische Realisierung

[cols="1,2"]
|===
| Programmiersprache | Java 21
| GUI-Framework | JavaFX
| Datenbanksystem | H2
| Architektur-Pattern | Model-View-Controller (MVC)
| Persistenz-Layer | JDBC
|===

[transition]

== Benutzeroberfläche

Zwei-Tab Interface:

[cols="1,1"]
|===
| Tab 1: Erfassung | Fahrten hinzufügen, bearbeiten, löschen
| Tab 2: Statistik | Kilometer, Durchschnitt, Fortschritt
|===

Intuitive Navigation und klare Datenübersicht



[transition]

== Mengengerüst und Skalierung

[cols="1,2"]
|===
| Benutzer pro Installation | 1
| Einträge pro Jahr | Circa 120 Fahrten
| Fahrten pro Woche | 2-3 durchschnittlich
|===


[transition]

== Ziele der Anwendung

* Vereinfachung der Fahrtenverwaltung
* Motivationssteigerung für Fahrschüler
* Digitale Alternative zu analogen Methoden
* Transparente Verfolgung des Fortschritts

[transition]

== Zusammenfassung

Die Lösung:

* Strukturierte und sichere Fahrtenverwaltung
* Eliminiert die Zettelwirtschaft
* Automatische Statistikberechnung
* Wartbar und benutzerfreundlich

[transition]

== Vielen Dank

Fragen?
