= Driving Tracker - Fahrtenverwaltung
:author: Jan Brunner
:email: j.brunner1@students.htl-leonding.ac.at
:revnumber: 1.0
:revdate: {docdate}
:revremark: JavaFX Anwendung zur Fahrtenverwaltung für Fahrschüler
:encoding: utf-8
:lang: de
:doctype: article
:revealjs_width: 1408
:revealjs_height: 792
:source-highlighter: highlightjs
:iconfont-remote!:
:iconfont-name: fonts/fontawesome/css/all
ifdef::env-ide[]
:imagesdir: ../images
endif::[]
ifndef::env-ide[]
:imagesdir: images
endif::[]
:title-slide-transition: fade
:title-slide-transition-speed: slow
:transition: fade
:transition-speed: slow

== Driving Tracker

[.text-center]
Digitale Fahrtenverwaltung für Fahrschüler

_Vereinfachte Verwaltung gefahrener Kilometer und Fahrtbedingungen_

[transition]

== Ausgangssituation

Fahrschüler in Österreich müssen ihre Fahrten dokumentieren:

[%step]
* Erforderlich für den Führerschein (L17 & Normalführerschein)
* Durchschnittlich 2-3 Fahrten pro Woche
* Circa 120 Einträge pro Jahr zu dokumentieren
* Notwendig für das Absolvieren des Führerscheins

[transition]

== Das Problem der Gegenwart

Aktuelle Vorgehensweise

[%step]
* Fahrtdaten werden manuell auf Zetteln notiert
* Dokumentation in Excel-Dateien oder ungeordnet
* Überblick über Kilometerstand geht schnell verloren
* Verwaltung vieler verstreuter Zetteln ist unübersichtlich
* Hoher zeitlicher Aufwand und Fehleranfälligkeit

[transition]

== Anforderungen an die Lösung

Funktionale Anforderungen

[%step]
* Neue Fahrten erfassen und speichern können
* Gespeicherte Fahrten bearbeiten oder löschen
* Gesamtkilometer und Durchschnittswerte anzeigen
* Übersichtliche Darstellung aller Fahrten

[transition]

== Anforderungen an die Lösung (Fortsetzung)

Nicht-funktionale Anforderungen

[%step]
* Daten müssen sicher und dauerhaft gespeichert sein
* Minimale Benutzeroberfläche mit zwei Tabs
** Tab 1: Fahrteneintragung
** Tab 2: Statistik und Übersicht
* Einfache und intuitive Bedienung

[transition]

== Lösungsansatz

JavaFX-Anwendung für strukturierte Fahrtenverwaltung

[%step]
* Zentrale Datenbank statt verstreute Zettel
* Systematische und strukturierte Erfassung aller Fahrtdaten
* Automatische Berechnung und Visualisierung von Statistiken
* Sicheres Backup und Persistenz der Daten
* Wartbar und zukünftig erweiterbar konzipiert

[transition]

== Use-Cases im Überblick

[plantuml, usecase, svg]
----
@startuml DrivingTracker_UseCase
left to right direction

actor Driver

package "Driving Tracker" {
    usecase UC1 as "Fahrt erfassen"
    usecase UC2 as "Fahrt bearbeiten"
    usecase UC3 as "Fahrt löschen"
    usecase UC4 as "Alle Fahrten anzeigen"
    usecase UC5 as "Nach Bedingungen filtern"
    usecase UC6 as "Fahrten sortieren"
    usecase UC7 as "Statistiken einsehen"
    usecase UC8 as "Fortschritt anzeigen"
}

Driver --> UC1
Driver --> UC2
Driver --> UC3
Driver --> UC4
Driver --> UC5
Driver --> UC6
Driver --> UC7
Driver --> UC8

UC1 .> UC4 : <<include>>
UC2 .> UC4 : <<include>>
UC3 .> UC4 : <<include>>
@enduml
----

[transition]

== Systemarchitektur

[plantuml, classdia, svg, width=100%, height=600]
----
@startuml
left to right direction

class Trip {
    -int id
    -LocalDate date
    -HashSet<Condition> conditions
    -double startKm
    -double endKm
    -String startCity
    -String endCity
    -String info
    
    +Trip(...)
    +addCondition()
    +getKilometers()
    +toStringCSV()
    +{static}parseFromCSV()
    +compareTo()
}

class TripManager {
    {static}-ObservableList<Trip> trips
    -DatabaseConnection connection
    -FilteredList<Trip> filteredList
    -SortedList<Trip> sortedList
    
    +loadTripsFromDB()
    +addTrip()
    +updateTrip()
    +deleteTrip()
    +applyFilter()
    +setSortedListComparator()
    +getSumKilometers()
    +getAverageKilometers()
}

class DatabaseConnection {
    {static}-String URL
    
    +insertIntoDB()
    +getAllTrips()
    +updateTrip()
    +deleteTrip()
    -defaultTables()
}

enum Condition {
    Day
    Night
    Rain
    Dry
    Wet
    Fog
    Snow
    Ice
}

Trip "1" --- "*" Condition : hat
TripManager "1" --- "*" Trip : verwaltet
TripManager "1" --- "1" DatabaseConnection : schreibt in

@enduml
----

Grundlage: Model-View-Controller Pattern mit drei Hauptkomponenten

[transition]

== Datenbankmodell

[plantuml, erd, svg]
----
@startuml DrivingTracker_ERD

entity TRIP {
    * ID : INT <<PK>>
    ---
    * DATE : DATE
    * START_KM : DOUBLE
    * END_KM : DOUBLE
    * START_CITY : VARCHAR(100)
    * END_CITY : VARCHAR(100)
    INFO : VARCHAR(1000)
}

entity TRIP_CONDITION {
    * TRIP_ID : INT <<FK>>
    * CONDITION_TYPE : VARCHAR(50)
    ---
    PRIMARY KEY (TRIP_ID, CONDITION_TYPE)
}

TRIP ||--o{ TRIP_CONDITION : hat

@enduml
----

Relationale Datenbankstruktur für sichere und konsistente Verwaltung

[transition]

== Technische Realisierung

[cols="1,2"]
|===
| Programmiersprache | Java 11 und höher
| GUI-Framework | JavaFX
| Datenbanksystem | H2
| Architektur-Pattern | Model-View-Controller (MVC)
| Persistenz-Layer | JDBC
| Collections | ObservableList, FilteredList, SortedList
|===

[transition]

== Benutzeroberfläche - Konzept

Tab-basiertes Interface mit zwei Hauptbereichen:

[%step]
* **Tab 1: Erfassung und Verwaltung**
  - Neue Fahrten hinzufügen
  - Bestehende Fahrten bearbeiten oder löschen
  - Übersichtliche Eingabefelder für alle Fahrtdaten

[%step]
* **Tab 2: Statistik und Analyse**
  - Gesamtkilometer anzeigen
  - Durchschnittswerte pro Fahrt berechnen
  - Fahrten pro Monat auswerten
  - Fortschrittsbalken für Lernfortschritt

[transition]

== Datenfluss und Reaktivität

Live-Datenmanagement durch Observable Collections:

[%step]
* ObservableList als zentrale Fahrtenverwaltung
* Automatische Benachrichtigung der UI bei Datenänderungen
* FilteredList für dynamische Filterung nach Bedingungen
* SortedList für flexible Sortierung nach Datumsangaben
* Konsistente Datenbanksynchronisation bei allen Operationen

[transition]

== Mengengerüst und Skalierung

[cols="1,2"]
|===
| Benutzer pro Installation | 1
| Einträge pro Jahr | Circa 120 Fahrten
| Fahrten pro Woche | 2-3 durchschnittlich
| Variabilität | Saisonal abhängig
|===

Ausgelegt für persönliche Nutzung mit ausreichender Erweiterbarkeit

[transition]

== Ziele der Anwendung

[%step]
* Vereinfachung der Verwaltung gefahrener Kilometer
* Anregung und Motivationssteigerung für Fahrschüler
* Digitale Alternative zu analogen Dokumentationsmethoden
* Transparente Verfolgung des Lernfortschritts
* Reduktion administrativer Belastung

[transition]

== Zusammenfassung

Die Driving Tracker Anwendung:

[%step]
* Bietet strukturierte und sichere Fahrtenverwaltung
* Eliminiert das Problem der Zettelwirtschaft
* Ermöglicht schnelle Übersicht und aussagekräftige Statistiken
* Reduziert Verwaltungsaufwand durch Automatisierung
* Ist wartbar, erweiterbar und benutzerfreundlich

[transition]

== Vielen Dank

Fragen?
