@startuml
left to right direction

class Trip {
    {static}-int lastId
    -int id <<get>>
    -LocalDate date <<get/set>>
    -HashSet<Condition> conditions <<get/set>>
    -double startKm <<get/set>>
    -double endKm <<get/set>>
    -String startCity <<get/set>>
    -String endCity <<get/set>>
    -String info <<get/set>>

    +Trip(date, conditions, startKm, endKm, startCity, endCity)
    +Trip(id, date, conditions, startKm, endKm, startCity, endCity)
    +Trip(id, date, conditions, startKm, endKm, startCity, endCity, info)
    +Trip(date, conditions, startKm, endKm, startCity, endCity, info)
    +Trip(other: Trip)
    +addCondition(condition: Condition)
    +toString(): String
    +toStringCSV(): String
    +{static}parseFromCSV(line: String): Trip
    +equals(o: Object): boolean
    +hashCode(): int
    +compareTo(o: Trip): int
}

class TripManager {
    {static}-ObservableList<Trip> trips
    -DatabaseConnection connection
    -FilteredList<Trip> filteredList
    -SortedList<Trip> sortedList
    -SimpleIntegerProperty countOfTrips

    +TripManager()
    +getCountProperty(): SimpleIntegerProperty
    +loadTripsFromDB()
    +addTrip(trip: Trip)
    +updateTrip(trip: Trip, old: Trip)
    +deleteTrip(trip: Trip)
    +getTripsSorted(): SortedList<Trip>
    +applyFilter(tripPredicate: Predicate<Trip>)
    +setSortedListComparator(val: Sort)
    +getCSV(): List<String>
    +getSumKilometers(): double
    +getAverageKilometers(): double
    +getTripsInMonth(month: Month): int
    +getKilometerInDates(dates: List<LocalDate>): double
    +clearTrips()
}

class DatabaseConnection {
    {static}-String URL

    +DatabaseConnection()
    +insertIntoDB(trip: Trip)
    +getAllTrips(): List<Trip>
    +updateTrip(trip: Trip, old: Trip)
    +deleteTrip(trip: Trip)
    -defaultTables()
}

enum Condition {
    Day
    Night
    Rain
    Dry
    Wet
    Fog
    Snow
    Ice
}

enum Sort {
    NEW
    OLD
}

Trip "1" --- "*" Condition : hat
TripManager "1" --- "*" Trip : verwaltet
TripManager "1" --- "1" DatabaseConnection : schreibt in
TripManager --- Sort : nutzt zum Sortieren

@enduml
