= Fahrtentracker
Jan Brunner
1.0.0, {docdate}:
:icons: font
:experimental:
:sectnums:
:source-highlighter: rouge
:docinfo: shared
ifndef::imagesdir[:imagesdir: images]
:toc:
ifdef::backend-html5[]
// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://github.com/JBrunnerhtl/Driving_Tracker_Java_Docs/main/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/JBrunnerhtl/Driving_Tracker_Java_Docs] ‏ ‏ ‎
endif::backend-html5[]

== Ausgangssituation

In Österreich gibt es jährlich sehr viele Fahrschüler, die sich für einen Führerschein anmelden. In Folge möchten sie diesen dann auch abschließen.

== Istzustand

Die meisten Fahrschüler schreiben ihre Kilometer, die sie fahren müssen, Analog auf oder in Excel nieder. Dies ist zum Beispiel beim Autoführerschein nötig.


== Problemstellung

Viele Fahrschüler verlieren schnell den Überblick, oder vergessen gefahrene Kilometer einzutragen. Zudem ist die Verwaltung von vielen Zetteln sehr unübersichtlich.


== Aufgabenstellung

Es soll eine JavaFX-App entwickelt werden, die dieses Problem löst.

=== Funktionelle Anforderungen

- Der Benutzer soll eine neue Fahrt hinzufügen können.
- Der Benutzer soll eine Fahrt, die falsche Daten beinhaltet, entweder löschen oder ändern können.
- Der Benutzer soll eine Übersicht haben, wo er wie viele Kilometer gefahren ist.
- Der Benutzer soll eine Aufsummierung der Kilometer haben.

=== Nicht funktionale Anforderungen

- Die Daten sollen sicher und persistent verwaltet werden
- Eine minimale UI mit zwei Tabs(Eintragung und Statistik) soll zur Verfügung stehen.
-

== Ziele

- Verwaltung von gefahrenen Kilometern vereinfachen
- Fahrschüler anregen den Führerschein zu machen


== Mengengerüst

- Benutzer: 1
- In der Woche fährt man durchschnittlich 2-3 Mal, wenn man den L17 macht (das sind ca. 120 einträge im Jahr). Beim normalen Führerschein auch das Gleiche.
- Eintragungszahl kann variieren, manchmal mehr manchmal weniger.


== Rahmenbedingungen

- JavaFX
- Datenbank: H2
- Pattern: MVC
